# Generated by Django 5.1.5 on 2025-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ticker", models.CharField(max_length=20)),
                ("open_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("adj_close", models.DecimalField(decimal_places=6, max_digits=10)),
                ("volume", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "rsi",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_signal",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_hist",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "percent_change",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "inflation",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "dxy",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "unique_together": {("date", "ticker")},
            },
        ),
    ]
