# Generated by Django 5.1.5 on 2025-02-13 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_data", "0004_userprofile_reset_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("prediction_date", models.DateField()),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "prediction_period",
                    models.CharField(
                        choices=[
                            ("1D", "One Day"),
                            ("1W", "One Week"),
                            ("1M", "One Month"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("features_used", models.JSONField()),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("PRICE", "Price Prediction"),
                            ("TREND", "Trend Prediction"),
                            ("VOLATILITY", "Volatility Prediction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PRICE", "Price Alert"),
                            ("TECHNICAL", "Technical Indicator"),
                            ("VOLUME", "Volume Alert"),
                            ("NEWS", "News Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("ABOVE", "Above"),
                            ("BELOW", "Below"),
                            ("CROSSES", "Crosses"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notification_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_position_size",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_daily_loss",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("max_total_risk", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "stop_loss_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "take_profit_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("max_trades_per_day", models.IntegerField()),
                ("risk_per_trade", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_management",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("exit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "leverage",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_profit_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "largest_gain",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "largest_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("average_holding_period", models.DurationField(null=True)),
                (
                    "risk_reward_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
