# Generated by Django 5.1.5 on 2025-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance_data",
            "0006_financialdata_atr_financialdata_close_200ma_diff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdata",
            name="economic_news",
            field=models.TextField(blank=True, null=True),
        ),
    ]
