# Generated by Django 5.1.5 on 2025-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_data", "0007_financialdata_economic_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdata",
            name="adj_close",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
    ]
